### ISSUE TITLE
Mint New Assets - NFT doesn't mint 

### ISSUE THREAD

**Issue by jrepusseau** [jogetoss/cardano-blockchain-pack#2]
Hello! 
I noticed that minting NFT with testnet and it always result to the same error: 
WARN 19 Aug 2022 14:52:05 org.joget.cardano.lib.CardanoMintTokenTool - jwc_root : Transaction failed with status code 500. Response returned --> Something went wrong
Please can you have a look at this issue? Its a real plus for Joget if this function can works correctly, 
May this issue linked with the recent IPFS gateway change? 
Thanks Joget dev teams,

**Comment by JustinWYL** [comment]
Hi @jrepusseau , while I attempt to replicate this on my end, can you paste a screenshot of your plugin configuration for the Cardano Mint Token Tool here? 
This is so I can replicate as close as possible to your settings.

Thank you.

**Comment by jrepusseau** [comment]
Hi @JustinWYL , I used the 7.0.7 alpha release ... and realized I was using old version of the cardano blockchin sample app example. By updating the the cardano blockchain app sample to the one updatesit solved the issue. Many thanks for your help!

**Comment by JustinWYL** [comment]
@jrepusseau Happy that the issue is resolved. You're welcome!

**Comment by jrepusseau** [comment]
Hi there, I think there is still an error in joget platform, 
When I try to mint two tokens one after the other, he will throw me 1) error 500 then 2) not enough fund
Im on the latest version
![error](https://user-images.githubusercontent.com/42121228/187941220-f90b5c75-51a8-4096-bcd8-9adef235b592.png)

**Comment by JustinWYL** [comment]
Hello @jrepusseau, I require a few clarifications:

1. Do attach the full error stack trace here for inspection.
2. Is this issue consistently replicable on that particular account?
3. Is this issue replicable on any other accounts? Try using another fresh account, fund with test ADA, and try minting.
4. Is the account sufficiently funded to perform minting transactions and its required fees?
5. If you have perform tons of test transactions on one account, it is possible that over time the account's UTXOs can become very large. Try consolidating the UTXOs (Basically just send ADA to yourself. For example, try with 50% of the total ADA you have. If this fails, try with incrementally smaller amounts and eventually it will free up UTXOs and should function normally again). Here's another explanation that may help you understand UTXO: [reddit - comment explaining UTXO](https://www.reddit.com/r/cardano/comments/cqhr39/comment/ewwrckw/?utm_source=share&utm_medium=web2x&context=3)
6. If you have perform tons of transactions and that particular account contains lots of different types of native tokens & NFTs, each UTXO the account contains has a minimum ADA requirement. For detailed explanation, see [min ada requirement docs](https://cardano-ledger.readthedocs.io/en/latest/explanations/min-utxo-mary.html)

**Comment by JustinWYL** [comment]
_Closed due to inactivity_
